#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Aug 04, 2019 11:41:24 AM IDT  platform: Darwin

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global FeedVar1
    FeedVar1 = tk.StringVar()
    global FeedVar2
    FeedVar2 = tk.StringVar()
    global CamVar1
    CamVar1 = tk.StringVar()
    global TraningVar
    TraningVar = tk.StringVar()
    global chb_Var
    chb_Var = tk.StringVar()

def R1Sel():
    print('ClientGUI_V2_support.R1Sel')
    sys.stdout.flush()

def R2Sel():
    print('ClientGUI_V2_support.R2Sel')
    sys.stdout.flush()

def R3Sel():
    print('ClientGUI_V2_support.R3Sel')
    sys.stdout.flush()

def on1L():
    print('ClientGUI_V2_support.on1L')
    sys.stdout.flush()

def on1R():
    print('ClientGUI_V2_support.on1R')
    sys.stdout.flush()

def on2L():
    print('ClientGUI_V2_support.on2L')
    sys.stdout.flush()

def on2R():
    print('ClientGUI_V2_support.on2R')
    sys.stdout.flush()

def onExit():
    print('ClientGUI_V2_support.onExit')
    sys.stdout.flush()

def onLogClear():
    print('ClientGUI_V2_support.onLogClear')
    sys.stdout.flush()

def onRunTraining():
    print('ClientGUI_V2_support.onRunTraining')
    sys.stdout.flush()

def onSetZero():
    print('ClientGUI_V2_support.onSetZero')
    sys.stdout.flush()

def onStatClear():
    print('ClientGUI_V2_support.onStatClear')
    sys.stdout.flush()

def onStatRun():
    print('ClientGUI_V2_support.onStatRun')
    sys.stdout.flush()

def onStopTraining():
    print('ClientGUI_V2_support.onStopTraining')
    sys.stdout.flush()

def onTankConfig():
    print('ClientGUI_V2_support.onTankConfig')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ClientGUI_V2
    ClientGUI_V2.vp_start_gui()




